### ISSUE TITLE
OCR stops working after 45 items

### ISSUE THREAD

**Issue by trollololsaurus** [compeanansi/epic7#10]
Hi Compenanansi,

Thanks for the great work out there but I've encountered this new issue. The processing stops at 45/XXX and throws me back this error

45 exported out of 375
currently processing screenshots\Screenshot_20200924-165104.png
screenshots\Screenshot_20200924-165104.png shows lvl 85 and enhance lv 10
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-0a37cfcc1a95> in <module>
     71                 if n <= 3:
     72                     stat = stat_converter(entry)
---> 73                     val = digit_filter(entry.replace('T','7'))
     74                     item['subStat'+str(n+1)] = [stat,val]
     75         if k == 'set':

<ipython-input-8-a15f785dd81b> in digit_filter(val)
     49     if not val: return 0
     50     elif val == '.': return 0
---> 51     else: return int(''.join(filter(str.isdigit,val)))
     52 
     53 def char_filter(val):

ValueError: invalid literal for int() with base 10: ''

**Comment by wsauret** [comment]
Please upload the offending image. This is a really common error type. It means it didn't get a value for that sub stat from the OCR library. I have no way to troubleshoot without the image.

**Comment by trollololsaurus** [comment]
Thanks for the swift response.
I was trying to redo the OCR several times and I would usually get an error throw back on the 45 or 46 item.

These are the 2 images:

![Screenshot_20200924-165101](https://user-images.githubusercontent.com/71820612/94181759-85d2e680-fed2-11ea-837f-f57080a0a31d.png)
![Screenshot_20200924-165057](https://user-images.githubusercontent.com/71820612/94181764-879caa00-fed2-11ea-95dc-22c6f5d0e22a.png)

**Comment by wsauret** [comment]
I just pushed a change to the script. try redownloading it and see if it works now. I downloaded your images and they processed just fine.

**Comment by trollololsaurus** [comment]
Thanks for the quick fix. It is working as intended now.
The digit error no longer stop the processing at its' track now.
