### ISSUE TITLE
I keep getting this error while running it

### ISSUE THREAD

**Issue by ghost** [compeanansi/epic7#11]
Hi can u please tell me how to fix this? I followed the guide and I still received the error. https://imgur.com/a/x4iVzCM

**Comment by wsauret** [comment]
I can tell from the code that is the old version of the notebook. please download the zip file of the repository again (step 4) so that you have the current version of the notebook.

**Comment by ghost** [comment]
https://imgur.com/a/MvDpwWi - I get value errors when i run all cells on the new code but at least it makes the json file, but when i import the json file to the gear optimizer application i get this error https://imgur.com/a/aepdvVO and then when i press okay, i get this error https://imgur.com/a/38bN6lt

**Comment by wsauret** [comment]
Please upload the screenshots that are failing so I can test them locally to try to figure out the issue. Also, please tell me the emulator you're using and emulator resolution.

**Comment by ghost** [comment]
https://imgur.com/a/2tY3KWD - Bluestacks emulator

**Comment by ghost** [comment]
also I changed my bluestacks resolution to 2200x1080 then i took a screenshot, checked the properties of the photo and it didnt even get to 2200

**Comment by wsauret** [comment]
That image isn't 2200x1080. It is 1228x684. The script will only work with properly sized screenshots. I tested Bluestacks myself just now and it looks like bluestacks doesn't take proper screenshots. I'll add it to the list of emulators that doesn't work properly in the instructions. You will need to take screenshots in an emulator that takes the screenshots at the internal resolution, like Nox or LDPlayer.

**Comment by ghost** [comment]
hmm okay.. but what if resized the screenshot manually in paint to 2200x1080 like this photo - https://imgur.com/a/II3eCcj do you think it will still work on the program?

**Comment by ghost** [comment]
I actually dont have the program but im asking this for my bf and hes currently asleep rn..

**Comment by wsauret** [comment]
No that won't work either because the placement of the item details differs depending on the resolution. Resizing a screenshot from a different base resolution will not move the item box into the correct position. (Also, I tested your sample resized screenshot, it does not work but its also not 2200x1080, it is 1393x684 so your resize didnt work).

**Comment by wsauret** [comment]
Maybe you should try uploading your images directly to github (drag them into the txt box) instead of imgur. It is possible imgur is resizing them so I cannot test them properly.

**Comment by ghost** [comment]
ah okay im sorry i didnt know u could upload pictures here on github.. 
![23](https://user-images.githubusercontent.com/38775102/94361251-868f9680-00e5-11eb-86ab-810b6dbf1c50.jpg)

**Comment by wsauret** [comment]
That worked better. The image was actually 2200x1080 via github upload. So on the resized images it'll read the stats, but not the item level, slot, or rarity. So resizing is not a proper fix.

**Comment by ghost** [comment]
what do i need to about it then? should i just use nox?

**Comment by wsauret** [comment]
Yes please just use nox.
