### ISSUE TITLE
Assertion Failed?

### ISSUE THREAD

**Issue by rayhwut** [compeanansi/epic7#12]
![image](https://user-images.githubusercontent.com/8931350/95417782-e404be00-0903-11eb-8b75-f0315e2c72fb.png)

I was originally using this through google colaboratory, but that wasn't working for me anymore so I'm trying to set this up offline. I'm on the step where I need to test the code, and I am getting the error above.

The only code I've changed is here:
![image](https://user-images.githubusercontent.com/8931350/95417876-21694b80-0904-11eb-8043-86b33958effe.png)

**Comment by wsauret** [comment]
please upload the image here (by dragging it into the github text box) so I can test it myself. also, if the relative path is still epic7-master/screenshots/ then you didn't need to change it at all. so long as your images are in a folder that is in the same folder as the ipynb, you can use the default settings. I would revert that change.

**Comment by rayhwut** [comment]
Hello I changed the relative path back, it now runs with no error, however the resulting json is empty.
![image](https://user-images.githubusercontent.com/8931350/95540508-f132b300-09be-11eb-9114-212b20d7d19e.png)

Here is the screen shot I used:
![Screenshot_2020-10-07-21-53-27](https://user-images.githubusercontent.com/8931350/95540487-e11ad380-09be-11eb-96ae-cdf19b2abd61.png)

**Comment by wsauret** [comment]
It worked fine for me. The path in the notebook was originally "sh_path = 'screenshots/'". Change it back to that and see if it works. Here is proof it worked fine for me:
![success](https://user-images.githubusercontent.com/6817460/95545400-11ce2d80-09fe-11eb-9625-cc1466bce942.png)

**Comment by rayhwut** [comment]
Hello! I have my drives split, and the directories got all messed up. Once I moved the code to where Anaconda was point originally, I was able to get it to work. Thanks!
