### ISSUE TITLE
OCR Stopped Processing 

### ISSUE THREAD

**Issue by trolololsaurus** [compeanansi/epic7#13]
Hi compeanansi,

I've encountered this error while processing the screenshots

> 49 exported out of 346
> currently processing screenshots\Screenshot_2020-10-08-10-29-10.png
> screenshots\Screenshot_2020-10-08-10-29-10.png shows lvl 85 and enhance lv 10
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-6-0a37cfcc1a95> in <module>
>      71                 if n <= 3:
>      72                     stat = stat_converter(entry)
> ---> 73                     val = digit_filter(entry.replace('T','7'))
>      74                     item['subStat'+str(n+1)] = [stat,val]
>      75         if k == 'set':
> 
> <ipython-input-5-a15f785dd81b> in digit_filter(val)
>      49     if not val: return 0
>      50     elif val == '.': return 0
> ---> 51     else: return int(''.join(filter(str.isdigit,val)))
>      52 
>      53 def char_filter(val):
> 
> ValueError: invalid literal for int() with base 10: ''

![Screenshot_2020-10-08-10-29-10](https://user-images.githubusercontent.com/45089996/95488244-e29cc980-09c7-11eb-9f5b-900195c53c97.png)

**Comment by trollololsaurus** [comment]
Apologies
Didn't realised you have an update 10 days ago.
Working as intended now

**Comment by trolololsaurus** [comment]
Apologies,
Didn't realised that you had made an update 10 days ago
Working as Intended now

**Comment by wsauret** [comment]
Very happy to hear that. Yeah, I added a bunch of improved error handling, so it should be much easier to offer support moving forward.
