### ISSUE TITLE
Error processing screenshots

### ISSUE THREAD

**Issue by Ningaal** [compeanansi/epic7#14]
My screenshots are 2200 x 1080 taken with Nox player 6.6.1.3 Android 7.

Error:
"Beginning export process...
currently processing not scanned1.png
ERROR: This screenshots is not 2200x1080!
Please retake the screenshot in Nox or LDPlayer with the internal resolution set to 2200x1080"

Sample:
 ![screenshots](https://user-images.githubusercontent.com/55004161/98661586-82b57d80-22fb-11eb-8b2e-de20f39a38ad.png)

**Comment by wsauret** [comment]
The screenshot I downloaded from your post wasn't 2200x1080, hence the error. You should verify that the original is 2200x1080 by opening it in an image editing program. Here is a screenshot from 'get info' in OSX. The dimensions are 1906x936:
<img width="254" alt="Screen Shot 2020-11-10 at 11 26 55 AM" src="https://user-images.githubusercontent.com/6817460/98662353-ee253c80-2347-11eb-9248-a60c933e2dce.png">

Can you show me the resolution settings in Nox that you're using? Are you using the built-in screenshot function?

**Comment by Ningaal** [comment]
Here they are. I'm using the "scissor" icon on Nox sidebar. 
![noxset](https://user-images.githubusercontent.com/55004161/98664651-7e8b5f00-22ff-11eb-83a1-681399cc06b6.PNG)

I have checked the dimensions of a few of my screenshots in properties. It seems all of them are in 1906 x 936. It's such an unusual number too for picture dimensions

**Comment by Ningaal** [comment]
I don't know if it is related but I have updated my graphics card this morning and now Nox takes screenshots as normal. I don't know if restarting Nox or updating graphics card is what fixed it for me.

**Comment by wsauret** [comment]
Glad you were able to get Nox to behave. It does sound like some weird kind of Nox error rather than a script error.
