### ISSUE TITLE
Regarding UI Update for Gear

### ISSUE THREAD

**Issue by ProtoNova29** [compeanansi/epic7#16]
First of all, thank you for your continued support thus far. You have created a system for us end game players to enjoy epic 7 outside of epic 7.

There has been a new UI update for gear that is causing the OCR to not parse it properly. I'm not sure if it is the positioning or the colors/font. But using the exact same emulator with no adjustment in settings I'm getting a large amount of errors when attempting to import.

All gear is coming in at an incorrect iLevel and enhance zero
Mmunity instead of Immunit
Lit instead of Crit
Ritical instead of Critical
Pic instead of Epic

[Sample Pictures](https://imgur.com/a/mtUj73o)

**Comment by ProtoNova29** [comment]
After looking a bit closer, it seems the substats aren't being picked up as well.

`"mainStat": ["", 525],
		"subStat1": ["CDmg", 8],
		"subStat2": ["", 20],
		"subStat3": ["", 15],
		"subStat4": ["CChance", 5],`

**Comment by calvadoz** [comment]
Yea, faced the same issues as well, substats are mainly missing. I believed it's due to the font size thickness changing or somewhere around it.

**Comment by ProtoNova29** [comment]
Just another bump. I connected with other members in the community experiencing similar problems. We are awaiting your glorious return!

**Comment by Hakim3i** [comment]
Same problem I hope this get fixed soon

**Comment by Hakim3i** [comment]
This is a potato fix tested on LDPlayer with 351 +15 item for those who can't wait for an update

https://pastebin.com/BGcxD9dZ

**Comment by wsauret** [comment]
Yeah, so the only thing that should need updating is the coordinates for the boxes for the screenshots. If the coordinates need updating, we could also move to another resolution if you guys prefer that. And that seems to be what @Hakim3i did, although he did it through slightly different code. I can also push through his coord changes to the main branch if you guys want.

I have quit playing E7, so I do not have access to screenshots of my own anymore, but it'd be a shame to see this script fall out of date, so I am always happy to merge pull requests or bug fixes moving forward. But after starting a new job (the reason I quit E7) I just don't have much free time to spend debugging the code.

**Comment by Hakim3i** [comment]
The bottom box is fine just need to change the main coordinates, but the top box need sub coordinate change, I changed them the item level is good but some items mainly event items have long frame and the item name and grade get cut in half I added lot of fix in replace function that's why I called it potato fix, I tried to cover most of the items that I had on +15.

Am sure that there is a better fix then what I did I never coded with python this is my first time trying.

**Comment by nhk2120** [comment]
@Hakim3i Thanks so much for the potato fix. I haven't tried it yet, but I'll try it now and check it out. I really waited for the fixes! By the way, would you be able to push the code to the git?

**Comment by wsauret** [comment]
Just because you're new, there is no reason to downplay your contribution @Hakim3i. You changed exactly what needed changing.

I pushed the new coordinates to the main branch. Please download the new ipynb and let us know if it works now. I will leave this issue open for a while so that people can report problems with the new coordinates if they arise.

I also really cleaned up the code in the script. I unpacked a bunch of the nested statements and improved the documentation via comments so that it will be much easier for everyone here to help keep this up to date in the future.

**Comment by nhk2120** [comment]
@compeanansi Got it! thanks for your work! As you said, this is a great tool and it would definitely be a waste to let it just out of date. Anyways, thank you again for your effort to keep it maintained!

**Comment by ProtoNova29** [comment]
Just wanted to thank you for your work once again and taking the time to do some cleanup even after the fact. All the best to you in your new job.  If there is ever an update that truly breaks the code then it certainly will be an end of an era for many of us!

**Comment by wsauret** [comment]
Pushed another update that allows you to easily print the various cropped images within the notebook and export them as png files. This should help with debugging the box coordinates moving forward. Just uncomment the lines in each section to enable them.

**Comment by ProtoNova29** [comment]
I just ran it based on my 550 pieces of gear and came up with these additional replacements if you anyone needs it:


Insert into Line 62 of @Hakim3i 's Code
`.replace('Nlaannn','Weapon').replace('Coic','Epic').replace('Epicr','Epic').replace('Halmoat','Helmet').replace('Halmot','Helmet').replace('Walmart','Helmet').replace('Llarnicr','Heroic').replace('Epicc','Epic').replace('Epiccr','Epic').replace('Ronnte','Boots').replace('Rannte','Boots').`

**Comment by calvadoz** [comment]
Hey @ProtoNova29 , just addition to that, I tried with my 630 pieces of gear too. Add on these as well from my findings
`.replace('Enir','Epic').replace('Llarnic','Heroic').replace('Wolmoat','Helmet')`

**Comment by wsauret** [comment]
Having to do so many replacements makes me think that the boxes still aren't exactly right. Is anyone able to pinpoint exactly which screenshots are throwing out these weird names? If you could upload them for me to test with, I can see if I can fix the root problem instead of just patching the symptoms with 100 replace functions.

**Comment by Hakim3i** [comment]
That's what I pointed out in my last comment I already added all the replacement in the pastbin link, problem with the some items mainly event items have long frame and the item name and grade get cut in half.

**Comment by llicemanz** [comment]
![Screenshot_2020-11-24-14-44-33](https://user-images.githubusercontent.com/48931350/100149477-19814e80-2e53-11eb-9083-f89fc4615407.png)
This is an example for me of the ones having issues, I'm testing some of the images to make sure we cover all scenarios. Will let you know if I find another example.

**Comment by wsauret** [comment]
@llicemanz fixed it for your image. Everyone else, please send me more problematic images so I can make sure it works for them all before pushing the change to main.
<img width="657" alt="Screen Shot 2020-11-24 at 10 03 36 PM" src="https://user-images.githubusercontent.com/6817460/100151126-04cba780-2ea1-11eb-87de-86f48673125c.png">

EDIT: Went ahead and pushed this change to live. I recommend everyone redownload the ipynb file and see if the newest version works better.

**Comment by llicemanz** [comment]
Awesome tested it and worked. I got two diff set of examples that it was not able to parse for two different reason. The first one it's saying critical error it was not able to identify them as Neck and the other one were index out of range.
![Screenshot_2020-11-24-17-44-02](https://user-images.githubusercontent.com/48931350/100166631-02058e00-2e72-11eb-906c-11cadc470078.png)
![Screenshot_2020-11-24-17-44-07](https://user-images.githubusercontent.com/48931350/100166635-029e2480-2e72-11eb-9ff3-706975dac6a9.png)
![Screenshot_2020-11-24-17-43-59](https://user-images.githubusercontent.com/48931350/100166636-0336bb00-2e72-11eb-8c51-1c75eda6528c.png)
![Screenshot_2020-11-24-16-50-22](https://user-images.githubusercontent.com/48931350/100166640-05991500-2e72-11eb-9835-051053694fb6.png)
![Screenshot_2020-11-24-16-50-26](https://user-images.githubusercontent.com/48931350/100166642-0631ab80-2e72-11eb-9281-cd708f834116.png)
![Screenshot_2020-11-24-16-50-29](https://user-images.githubusercontent.com/48931350/100166643-0631ab80-2e72-11eb-9022-92ab70796a61.png)

Awesome work btw THANK YOU!

**Comment by wsauret** [comment]
@llicemanz pushed a fix right now that makes it work for all those screenshots.

**Comment by calvadoz** [comment]
thanks for the hard work again @compeanansi , you sure help a lot of people

**Comment by llicemanz** [comment]
I verified 400 items and all of them were good no errors or anything. I think we can close this bug! I'm gonna study your changes later for next time see if I can do fixes myself. Thank you so much for helping!
