### ISSUE TITLE
Error importing

### ISSUE THREAD

**Issue by lollirenzo** [compeanansi/epic7#17]
Hi guys. I'm getting an error saying something like "Nil Rg value" (sorry but i got that error in italian, so i can't say if that is the correct error in english) and followed by another error saying "Corrupted or wrong file format. Please select a json file exported by etc etc".
I followed the guide step by step and used this a couple months ago already without any error. File format is 100% correct but i dunno why i'm still getting that error. Tried doing the exported_gear.json file multiple times, still the same error.

**Comment by llicemanz** [comment]
If it's on the optimizer that you are getting this error make sure you are using the option  "Import JSON from the web optimizer" when importing

**Comment by lollirenzo** [comment]
Yeh, using the web optimazer option

**Comment by llicemanz** [comment]
That means there is a value in the json that it's not ring, check for things like rina instead of ring and others.

**Comment by lollirenzo** [comment]
Plus, i noticed that every +0 item is listed as +1, others as +19 instead of +15

**Comment by compeanansi** [comment]
yeah the ocr isnt perfectly accurate

**Comment by wsauret** [comment]
I'm not really able to troubleshoot optimizer problems, but maybe someone else can. However, I did push an update that will default enhance levels to 0 instead of 1 when the ocr fails, and I put a check in to ensure enhance lvl can never be > 15.

**Comment by lollirenzo** [comment]
Tried with the new update and took all screenshots all over again, thinking that may be a screenshots problem but i even get errors running the new screenshots now (it process correctly all +15 items and fails all the +0 gear). I tried both old and new screenshots:

currently processing screenshots\Screenshot_20201127-125727.png
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-d7d695631248> in <module>
    101     data = iterative_process(plus_img)
    102     #data = data.replace('S','5').replace('B','8').replace('a','8') # Fix common OCR errors
--> 103     data = digit_filter(data)
    104     if data > 15: data = 15
    105     item['ability'] = data

<ipython-input-4-3987198f242f> in digit_filter(val)
     59     # This attempts to filter out all characters that are not digits
     60     # If there are no digits, then it returns 0
---> 61     try: return int(''.join(filter(str.isdigit,val)))
     62     except ValueError: return 0
     63 

TypeError: 'int' object is not iterable

**Comment by wsauret** [comment]
That error suggests to me that I need to make sure to set 'val' to a string so that the digit filter works no matter what is passed in. I pushed a new version just now. Let me know if it doesn't fix that error.

**Comment by lollirenzo** [comment]
It does compile the json file now but it has 2 errors:
- all the +0 rings with flat ATK as main stat turns to +7 and 500 flat ATK
- all the +0 necklaces with %ATK as main stat turns to 50-60 %ATK

**Comment by wsauret** [comment]
That's a feature, not an error, lol. If you do not want it to set the stats to max, then disable it in the first sell by setting 'assume_max_lv_gear' to False.

**Comment by lollirenzo** [comment]
O really? Well, actually i though it was a bug so i posted it, but it's a good feature honestly. Looks to be everything ok atm then

**Comment by wsauret** [comment]
Happy to hear it. Glad everything is working now.
