### ISSUE TITLE
Restart issue

### ISSUE THREAD

**Issue by MrQuestSD** [compeanansi/epic7#3]
Any clue on what to do to fix the following error that's running?

== RESTART: C:\Users\xxxxxxx\Desktop\epic7-master\e7_ocr_gear_2200x1080.py ==
Traceback (most recent call last):
  File "C:\Users\xxxxxx\Desktop\epic7-master\e7_ocr_gear_2200x1080.py", line 136, in <module>
    cv2.matchTemplate(cv2.cvtColor(img, cv2.COLOR_BGR2GRAY), temp_top, cv2.TM_CCOEFF_NORMED))
cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

**Comment by wsauret** [comment]
The .py file was pushed to the repository by someone else and I don't provide support for it. I removed it and updated the instructions on how to use the supported .ipynb file.
