### ISSUE TITLE
Step 5 and Permission error

### ISSUE THREAD

**Issue by Eoryu** [compeanansi/epic7#5]
Sorry, I'm not good at code stuff, but what does Step 5 mean? What Repository? On the main page of Anaconda? there is no download or clone button to use. I skipped it and got to the run all cells part, but when I do that I get a permission error when JupyterLab tries to make the JSON.

**Comment by wsauret** [comment]
The github page you're on right now is my github repository. You download it from here.
<img width="491" alt="Screen Shot 2020-05-28 at 9 43 19 PM" src="https://user-images.githubusercontent.com/6817460/83186115-4cf55180-a12c-11ea-8098-54d54b4d7b5d.png">

**Comment by Eoryu** [comment]
OH! Ok, so I was just ahead and it kind of threw me off after Step 4. So, then I get this error when I try to run the thing on JupyterLabs

Beginning export process...
currently processing screenshots\Screenshot_20190322-115231.jpg
---------------------------------------------------------------------------
PermissionError                           Traceback (most recent call last)
<ipython-input-2-957a4b8c9fe0> in <module>
     46 
     47     for k in top_coords.keys():
---> 48         data = process(k,top_box[top_coords[k][0][0]:top_coords[k][0][1],top_coords[k][1][0]:top_coords[k][1][1]])
     49         if k == 'type':
     50             item['rarity'] = char_filter(data.split(' ')[0])

<ipython-input-1-ce1e7f7721a2> in process(k, img)
     35         low = 70
     36         proc = cv2.cvtColor(cv2.medianBlur(cv2.threshold(cv2.cvtColor(cv2.resize(img, (0, 0), fx=5, fy=5), cv2.COLOR_BGR2GRAY), low, 255, thresh)[1], 3), cv2.COLOR_GRAY2RGB)
---> 37         data = image_to_string(Image.fromarray(proc), lang='eng', config='--psm 6').replace('Rina','Ring').replace('Edic','Epic').replace('Enic','Epic')
     38     return data
     39 

D:\Anaconda\lib\site-packages\pytesseract\pytesseract.py in image_to_string(image, lang, config, nice, output_type, timeout)
    358         Output.DICT: lambda: {'text': run_and_get_output(*args)},
    359         Output.STRING: lambda: run_and_get_output(*args),
--> 360     }[output_type]()
    361 
    362 

D:\Anaconda\lib\site-packages\pytesseract\pytesseract.py in <lambda>()
    357         Output.BYTES: lambda: run_and_get_output(*(args + [True])),
    358         Output.DICT: lambda: {'text': run_and_get_output(*args)},
--> 359         Output.STRING: lambda: run_and_get_output(*args),
    360     }[output_type]()
    361 

D:\Anaconda\lib\site-packages\pytesseract\pytesseract.py in run_and_get_output(image, extension, lang, config, nice, timeout, return_bytes)
    268         }
    269 
--> 270         run_tesseract(**kwargs)
    271         filename = kwargs['output_filename_base'] + extsep + extension
    272         with open(filename, 'rb') as output_file:

D:\Anaconda\lib\site-packages\pytesseract\pytesseract.py in run_tesseract(input_filename, output_filename_base, extension, lang, config, nice, timeout)
    239     except OSError as e:
    240         if e.errno != ENOENT:
--> 241             raise e
    242         raise TesseractNotFoundError()
    243 

D:\Anaconda\lib\site-packages\pytesseract\pytesseract.py in run_tesseract(input_filename, output_filename_base, extension, lang, config, nice, timeout)
    236 
    237     try:
--> 238         proc = subprocess.Popen(cmd_args, **subprocess_args())
    239     except OSError as e:
    240         if e.errno != ENOENT:

D:\Anaconda\lib\subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors, text)
    798                                 c2pread, c2pwrite,
    799                                 errread, errwrite,
--> 800                                 restore_signals, start_new_session)
    801         except:
    802             # Cleanup if the child failed starting.

D:\Anaconda\lib\subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_start_new_session)
   1205                                          env,
   1206                                          os.fspath(cwd) if cwd is not None else None,
-> 1207                                          startupinfo)
   1208             finally:
   1209                 # Child is launched. Close the parent's copy of those pipe

PermissionError: [WinError 5] Access is denied
​
It's kinda long but I keep seeing permission error, any idea how to fix that?

**Comment by wsauret** [comment]
Two things come to mind. First, did you do this part? "Next, make sure the path to tesseract listed in these two lines is the same as the one tesseract was installed to earlier." It could be failing because it's not finding the tesseract binary.

Second, you should try running everything as administrator. It's possible that if you're on a user account without admin privileges that this is causing the error.

**Comment by SeMro25** [comment]
Hey, I have the same problem. The path to tesseract is 100% correct, because when I change it on purpose, it shows another error about being unable to find it. Pretty sure everything is running as adminstrator too.

**Comment by Eoryu** [comment]
Yeah i set them to where i installed Tesseract.

pytesseract.pytesseract.tesseract_cmd = "D:\Tesseract-OCR"
TESSDATA_PREFIX = r"D:\Tesseract-OCR"

I run Anaconda as admin but jupyterlab is in the browser unless there's another way to launch it. Using the notebook Jupiter gets the same error.

**Comment by wsauret** [comment]
I haven't seen this error before, I'd have to try doing a fresh install myself to see if I can figure this out.

**Comment by Eoryu** [comment]
I found this through a reddit comment and he was having an error as well, I don't know if it was the same thing but he said he changed from python 3.7 to 3.6, and then it worked. I have no idea how to do that, but maybe that might fix it?

**Comment by SeMro25** [comment]
I've tried on python 3.6.1 and 3.6.0, got the same permission error.

**Comment by wsauret** [comment]
I just uninstalled anaconda and tesseract, redownloaded anaconda and tesseract (although I used an updated version found here: https://digi.bib.uni-mannheim.de/tesseract/tesseract-ocr-w64-setup-v5.0.0-alpha.20200328.exe), did the pip installs, opened the notebook, uncommented the lines (and changed the paths), and it ran just fine with no errors. Maybe you should try uninstalling tesseract and installing this updated version?

<img width="455" alt="success" src="https://user-images.githubusercontent.com/6817460/83190514-87e19000-a100-11ea-9089-19e9f34a9a02.PNG">
If you're still having problems after updating tesseract, you might try running the ipynb file through "Notebook" instead of "JupyterLab" in Anaconda Navigator. The process is basically the same this is just the old version of the program.

**Comment by SeMro25** [comment]
I've reinstalled tesseract (the newest version) - to the default directory this time, and it works now! Thank you

**Comment by wsauret** [comment]
Using the default directory could matter too. I'll suggest that in the instructions. But I won't close this issue until I hear back from @Eoryu.

**Comment by Eoryu** [comment]
I just tried default installs for everything, same error

**Comment by SeMro25** [comment]
Did you change tesseract directory manually? Use the default one (copy and paste those):
pytesseract.pytesseract.tesseract_cmd = "C:/Program Files/Tesseract-OCR/tesseract"
TESSDATA_PREFIX = r"C:\Program Files\Tesseract-OCR"

**Comment by Eoryu** [comment]
OH! Ok, now it worked! I had the top one without the /tesseract at the end. But it's working now

Thanks for everything!

**Comment by wsauret** [comment]
Hurray, glad it is working for everyone now.
