### ISSUE TITLE
Error while processing screenshots

### ISSUE THREAD

**Issue by Zaum11** [compeanansi/epic7#6]
Hey, 
when trying to use your code I run into errors. Sadly I have no idea on what to make of it so I was hoping you might be able to help. 
The error is "ValueError: invalid literal for int() with base 10:", and I pasted you the most recent traceback I got (I have gotten a different one before but cant reproduce it anymore):
```
currently processing screenshots\MuMu20200621204338.png
screenshots\MuMu20200621204338.png shows lvl 75 and enhance lv 15
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-14-957a4b8c9fe0> in <module>
     73             for n,entry in enumerate(data.split('\n')):
     74                 stat = stat_converter(entry)
---> 75                 val = digit_filter(entry.replace('T','7'))
     76                 item['subStat'+str(n+1)] = [stat,val]
     77         if k == 'set':

<ipython-input-13-bea55c8c2182> in digit_filter(val)
     63         return 0
     64     else:
---> 65         return int(''.join(filter(str.isdigit,val)))
     66 
     67 def char_filter(val):

ValueError: invalid literal for int() with base 10: ''
```
 What is weird to me is that the error does not appear on every screenshots I feed into the programm. For example on the test screenshot and on maybe half of my own screenshots I end up with a proper .json file, however with the other half I run into the aforementioned type of error. 

I have tried to narrow it down a bit more, but I cant seem to find any common denominator. If I use the same type of ring as the one in your test screenshot I run into the error.
Furthermore on 2 of the same items with identical description, substats, level and enhancement-level and merely different substat ranges I only run into the error on one of them.

I hope you can help and that the information I provided helps you out. 
Best regards
Zaum

**Comment by Zaum11** [comment]
Update:
It seems that this is an issue specific to certain emulators taking screenshots weird.
It works when using screenshots taken in nox, however using screenshots taken with MuMu emulator does not work, even if its the correct resolution.

**Comment by wsauret** [comment]
Sorry for not responding quicker. As you surmised, the error was a result of the filter function receiving a blank input and throwing an error when it was expecting a string. The input was blank, presumably, because the location of the OCR detection box did not line up with the correct area on the screenshot. I have added a note on the instructions to avoid using MuMu for the screenshots. Thank you!
