### ISSUE TITLE
Error when processing test screenshot

### ISSUE THREAD

**Issue by forumfodder** [compeanansi/epic7#8]
Hi 

I've been trying to setup the OCR and following the readme file and trying to test the setup using the screenshot provided in the package (ie /screenshots/Screenshot_20190322-115231.jpg) and I am getting the following error:

Beginning export process...
currently processing screenshots\Screenshot_20190322-115231.jpg
screenshots\Screenshot_20190322-115231.jpg shows lvl 85 and enhance lv 15

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-30-0e4b120252e0> in <module>
     70             for n,entry in enumerate(data.split('\n')):
     71                 stat = stat_converter(entry)
---> 72                 val = digit_filter(entry.replace('T','7'))
     73                 item['subStat'+str(n+1)] = [stat,val]
     74         if k == 'set':

<ipython-input-29-a15f785dd81b> in digit_filter(val)
     49     if not val: return 0
     50     elif val == '.': return 0
---> 51     else: return int(''.join(filter(str.isdigit,val)))
     52 
     53 def char_filter(val):

ValueError: invalid literal for int() with base 10: ''

When I comment out line 72 and run the script it processes the file without and error but the main stat and sub stat values are incorrect in the exported file.

I have re-installed everything few times and re-followed the readme steps but just can't figure out what I am doing wrong.

Thanks

**Comment by meowzor90-web** [comment]
Same issue as forum fodder, I tested both test screenshot and Noxplayer 2200/1080 resolution screenshot with same error. appreciate your help, thanks.

**Comment by Pariah** [comment]
Same issue myself I'm afraid. 

Windows 10 Pro, Version 2004, OS Build 19041.450

**Comment by wsauret** [comment]
Sorry for taking so long to fix this. It was a super simple error. For whatever reason, it was generating more than four values for sub stat entries and when it tried to parse the noise in the 5th entry it (understandably) failed. Now it only parses the first four values, since there will never be more than four.
